name: flutter_app
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  generic_bloc_provider: ^1.0.9
  cupertino_icons: ^0.1.3
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.3
  cloud_firestore: ^0.14.2
  image_picker: ^0.6.7+12
  firebase_storage: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true



  assets:
    - assets/img/people.jpg
    - assets/img/ann.jpg
    - assets/img/girl.jpg
    - assets/img/mountain.jpeg
    - assets/img/beach.jpeg
    - assets/img/beach_palm.jpeg
    - assets/img/mountain_stars.jpeg
    - assets/img/sunset.jpeg
    - assets/img/river.jpeg

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf